// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetSession;

#nullable disable

namespace ProjetSession.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ProjetSession.Models.Entretiens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Etat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kilometrage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeEntretien")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Entretiens");
                });

            modelBuilder.Entity("ProjetSession.Models.VehiculeConstruction", b =>
                {
                    b.Property<string>("Vin")
                        .HasColumnType("TEXT");

                    b.Property<int>("Annee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoiteVitesse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carburant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChevauxVapeur")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Consommation")
                        .HasColumnType("REAL");

                    b.Property<int>("Couleur")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DateAchat")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EstHomologueRoute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtatHuile")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtatMoteur")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtatPneus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtatTransmission")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kilometrage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Marque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modele")
                        .HasColumnType("TEXT");

                    b.Property<double>("NombreCylindres")
                        .HasColumnType("REAL");

                    b.Property<int>("NombrePassagers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombrePortes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombreRoues")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermisSpecial")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PrixConstructeurAchat")
                        .HasColumnType("REAL");

                    b.Property<double>("PrixConstructeurActuel")
                        .HasColumnType("REAL");

                    b.Property<int>("Transmission")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeVehicule")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VitesseMax")
                        .HasColumnType("INTEGER");

                    b.HasKey("Vin");

                    b.ToTable("VehiculeConstructions");
                });

            modelBuilder.Entity("ProjetSession.Models.VehiculeLourd", b =>
                {
                    b.Property<string>("Vin")
                        .HasColumnType("TEXT");

                    b.Property<int>("Annee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoiteVitesse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carburant")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ChargementMax")
                        .HasColumnType("REAL");

                    b.Property<int>("ChevauxVapeur")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Consommation")
                        .HasColumnType("REAL");

                    b.Property<int>("Couleur")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DateAchat")
                        .HasColumnType("TEXT");

                    b.Property<int>("Domaine")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtatHuile")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtatMoteur")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtatPneus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtatTransmission")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Hauteur")
                        .HasColumnType("REAL");

                    b.Property<int>("Kilometrage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Marque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modele")
                        .HasColumnType("TEXT");

                    b.Property<double>("NombreCylindres")
                        .HasColumnType("REAL");

                    b.Property<int>("NombrePassagers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombrePortes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombreRoues")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermisRequis")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PoidsMax")
                        .HasColumnType("REAL");

                    b.Property<double>("PrixConstructeurAchat")
                        .HasColumnType("REAL");

                    b.Property<double>("PrixConstructeurActuel")
                        .HasColumnType("REAL");

                    b.Property<int>("Transmission")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VitesseMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VitesseMaxAutorisee")
                        .HasColumnType("INTEGER");

                    b.HasKey("Vin");

                    b.ToTable("VehiculeLourds");
                });

            modelBuilder.Entity("ProjetSession.Models.VehiculePromenade", b =>
                {
                    b.Property<string>("Vin")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AEssuieGlacesArriere")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ARoueDeSecours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Annee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoiteVitesse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carburant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carrosserie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChevauxVapeur")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Consommation")
                        .HasColumnType("REAL");

                    b.Property<int>("Couleur")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DateAchat")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EstDecapotable")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("EstSportive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtatHuile")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtatMoteur")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtatPneus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtatTransmission")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kilometrage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Marque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modele")
                        .HasColumnType("TEXT");

                    b.Property<double>("NombreCylindres")
                        .HasColumnType("REAL");

                    b.Property<int>("NombrePassagers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombrePortes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombreRoues")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PrixConstructeurAchat")
                        .HasColumnType("REAL");

                    b.Property<double>("PrixConstructeurActuel")
                        .HasColumnType("REAL");

                    b.Property<int>("Transmission")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VitesseMax")
                        .HasColumnType("INTEGER");

                    b.HasKey("Vin");

                    b.ToTable("VehiculePromenades");
                });
#pragma warning restore 612, 618
        }
    }
}
